-- -- enable extension (once)
-- CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- INSERT INTO fact_train_movements (
--     movement_id,
--     observation_date,
--     station_key,
--     train_key,
--     planned_arrival,
--     actual_arrival,
--     arrival_status,
--     planned_departure,
--     actual_departure,
--     departure_status
-- )
-- WITH matches AS (
--     SELECT 
--         s.stop_id, 
--         s.station_name_normalized, 
--         d.station_name_normalized AS match_name,
--         d.eva_id AS station_id, 
--         similarity(s.station_name_normalized, d.station_name_normalized) AS sim
--     FROM staging_movements s
--     JOIN dim_stations d
--       ON LEFT(s.station_name_normalized, 4) = LEFT(d.station_name_normalized, 4)
--      AND similarity(s.station_name_normalized, d.station_name_normalized) > 0.4
-- ), best_matches AS (
--     SELECT DISTINCT ON (stop_id) stop_id, station_id, sim
--     FROM matches
--     ORDER BY stop_id, sim DESC
-- )
-- SELECT 
--     s.stop_id AS movement_id,
--     s.observation_date,
--     m.station_id AS station_key,
--     s.trip_id AS train_key,
--     s.arrival_planned AS planned_arrival,
--     s.arrival_actual AS actual_arrival,
--     s.arrival_status,
--     s.departure_planned AS planned_departure,
--     s.departure_actual AS actual_departure,
--     s.departure_status
-- FROM staging_movements s
-- JOIN best_matches m
--   ON s.stop_id = m.stop_id;