-- -- 1. Dimension: Stations
-- CREATE TABLE IF NOT EXISTS dim_stations (
--     eva_id BIGINT PRIMARY KEY,
--     station_name TEXT NOT NULL,
--     latitude DOUBLE PRECISION,
--     longitude DOUBLE PRECISION
-- );

-- -- 2. Dimension: Trains
-- CREATE TABLE dim_trains (
--     trip_id TEXT PRIMARY KEY,
--     train_number TEXT,
--     train_category TEXT,
--     operator TEXT
-- );

-- -- 3. Staging table: raw movements
-- CREATE TABLE staging_movements (
--     stop_id TEXT PRIMARY KEY,        -- use stop_id as unique identifier
--     observation_date DATE,
--     trip_id TEXT REFERENCES dim_trains(trip_id),
--     station_xml_name TEXT,
--     arrival_planned TIMESTAMP,
--     arrival_actual TIMESTAMP,
--     arrival_status CHAR(1),
--     departure_planned TIMESTAMP,
--     departure_actual TIMESTAMP,
--     departure_status CHAR(1)
-- );

-- -- 4. Fact table: clean movements
-- CREATE TABLE IF NOT EXISTS fact_train_movements (
--     movement_id TEXT PRIMARY KEY,   -- same as stop_id from staging
--     observation_date DATE,
--     station_key BIGINT REFERENCES dim_stations(eva_id),
--     train_key TEXT REFERENCES dim_trains(trip_id),
--     planned_arrival TIMESTAMP,
--     actual_arrival TIMESTAMP,
--     arrival_status CHAR(1),
--     planned_departure TIMESTAMP,
--     actual_departure TIMESTAMP,
--     departure_status CHAR(1)
-- );
